import JPic from "../../../public/images/hero-image.png";

export const props = [
  {
    id: 1,
    image: JPic,
    cost: 20.0,
    location: "Yaoundé, Messassi",
    category: "For Rent",
    description: "Appartment",
  },
  {
    id: 2,
    image: JPic,
    cost: 0,
    location: "Bonaberi, Douala",
    category: "For Sale",
    description: "Appartment",
  },
  {
    id: 3,
    image: JPic,
    cost: 0,
    location: "Yaoundé, Messassi",
    category: "For Rent",
    description: "Appartment",
  },
  {
    id: 4,
    image: JPic,
    cost: 20.0,
    location: "Bonaberi, Douala",
    category: "For Sale",
    description: "Appartment",
  },
  {
    id: 5,
    image: JPic,
    cost: 0,
    location: "Yaoundé, Messassi",
    category: "For Rent",
    description: "Appartment",
  },
  {
    id: 6,
    image: JPic,
    cost: 0,
    location: "Bonaberi, Douala",
    category: "For Sale",
    description: "Appartment",
  },
  {
    id: 7,
    image: JPic,
    cost: 20.0,
    location: "Yaoundé, Messassi",
    category: "For Rent",
    description: "Appartment",
  },
  {
    id: 8,
    image: JPic,
    cost: 0,
    location: "Bonaberi, Douala",
    category: "For Sale",
    description: "Appartment",
  },
  {
    id: 9,
    image: JPic,
    cost: 0,
    location: "Yaoundé, Messassi",
    category: "For Rent",
    description: "Appartment",
  },
  {
    id: 10,
    image: JPic,
    cost: 20.0,
    location: "Bonaberi, Douala",
    category: "For Sale",
    description: "Appartment",
  },
];
